### ISSUE TITLE
"Help/Contents" menu item not working

### ISSUE THREAD

**Issue by RatcheT2497** [DragoniteSpam/DDDEditorGMS2#4]
Shows message "Cannot open the file: Overview::.htm"

**Comment by DragoniteSpam** [comment]
I officially decided to use tooltips as the primary documentation, instead of trying to get myself to write an actual document - at least for now.

![image](https://user-images.githubusercontent.com/7087495/74264199-443c5500-4cce-11ea-8728-bb8c3293c1c7.png)

The menu entry is still there but it doesn't do anything, I'll leave it for now in the event that I decide to write something properly in the future.
